// Code generated by wit-bindgen-go. DO NOT EDIT.

package ui

import (
	"go.bytecodealliance.org/cm"
)

func lower_TupleU32U32(v [2]uint32) (f0 uint32, f1 uint32) {
	f0 = (uint32)(v[0])
	f1 = (uint32)(v[1])
	return
}

func lower_OptionTupleU32U32(v cm.Option[[2]uint32]) (f0 uint32, f1 uint32, f2 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2 := lower_TupleU32U32(*some)
		f1 = (uint32)(v1)
		f2 = (uint32)(v2)
	}
	return
}

func lower_PopupAnchor(v PopupAnchor) (f0 uint32, f1 uint64) {
	f0 = (uint32)(v.Tag())
	switch f0 {
	case 0: // position
		v1 := (uint64)(*cm.Case[Offset](&v, 0))
		f1 = (uint64)(v1)
	}
	return
}
