// Code generated by wit-bindgen-go. DO NOT EDIT.

package syntax

import (
	"go.bytecodealliance.org/cm"
)

func lower_Node(v Node) (f0 uint64, f1 *uint8, f2 uint32, f3 uint32, f4 uint64, f5 uint64) {
	f0 = (uint64)(v.ID)
	f1, f2 = cm.LowerString(v.Kind)
	f3 = (uint32)(cm.BoolToU32(v.Named))
	f4 = (uint64)(v.Start)
	f5 = (uint64)(v.End)
	return
}
