// Code generated by wit-bindgen-go. DO NOT EDIT.

package events

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// BufferChangeShape is used for storage in variant or result types.
type BufferChangeShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(BufferChange{})]byte
}
